### ISSUE TITLE
Beginner Room alts

### ISSUE THREAD

**Issue by 3rth** [TB-FAQ/TB-FAQ#46]
"Playing in official beginner rooms on an alternate account will result in you receiving an IP ban from the beginner rooms. Leave the beginner rooms to legitimate beginners."
Lines 90-93
Hey, I wasn't aware this was a thing and wanted to double check. Is this something that's actively enforced? While I appreciate the sentiment it seems unrealistic given that people come back after years, or (as I did when I first started playing) making multiple accounts. 
If it is enforced, then I feel it needs clarifying to exclude people who have for whatever legitimate reason made a new account. In addition how do you tell? One can argue it's relatively easy to tell someone new however that feels in the same vein as "soft rules", which we don't support/do.

**Comment by suomy** [comment]
Would affect [ingame_rules.html](https://github.com/TB-FAQ/TB-FAQ/blob/master/FAQ%20Items/Rules/ingame_rules.html).

**Comment by Karbn** [comment]
hey there. yes, HS follows this rule and it's still in effect. we follow it, unless there's an exception, such as said person forgot their main account password. in that case, we help the person to get their main back, and still ban the alt from the server once everything is dealt with. this rule also stays in effect unless the person coming back to the game is 5 years or older (inactive).
