### ISSUE TITLE
/status displays IPs?

### ISSUE THREAD

**Issue by suomy** [TB-FAQ/TB-FAQ#53]
I've heard conflicting information regarding whether or not `/status` shows IPs for non-admin accounts. I believe that was removed at some point in the more recent past, since it led to DDoS attacks on other players. If someone can test this, that would be appreciated. This would affect [operator_commands.html](https://github.com/TB-FAQ/TB-FAQ/blob/master/FAQ%20Items/Game/operator_commands.html).

**Comment by Novaras** [comment]
only ingame admins can use /status, removed from `option_commands.html`
